### ISSUE TITLE
mmcv version

### ISSUE THREAD

**Issue by hduer** [open-mmlab/mmaction2#645]
Traceback (most recent call last):
  File "tools/test.py", line 196, in <module>
    main()
  File "tools/test.py", line 134, in main
    if cfg.test_cfg is None:
  File "/home/cb/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 363, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/cb/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_cfg'

when i test model, above error happened, i try to uninstall mmcv and reinstall mmcv=1.1.6.  
but error also happend

**Comment by congee524** [comment]
Sorry, It's a bug introduced by #629, you can roll back the version and I'll fix it as soon as possible.

**Comment by dreamerlin** [comment]
> Sorry, It's a bug introduced by #629, you can roll back the version and I'll fix it as soon as possible.

Pay attention to BC (Backwards compatibility)
